### ISSUE TITLE
Two dupes found; one of them is not

### ISSUE THREAD

**Issue by dpordomingo** [src-d/lookout-gometalint-analyzer#25]
The analyzer returns two suggestions for the same line; one is ok, the other is not:
(e.g. at https://github.com/src-d/lookout/pull/442/commits/52e1fa8a904ae92161e0dd977e46ed4428d2a723#r244591876 )

given this piece of code:
```go
	getAnalyzerNotifier := func(ctx context.Context, settings map[string]interface{}) (analyzerNotifier, error) {
		st := grpchelper.ToPBStruct(settings)
		switch ev := e.(type) {
		case *lookout.ReviewEvent:
			if st != nil {
				ev.Configuration = *st
			}
			return analyzerNotifier{
				func(ctx context.Context, a lookout.AnalyzerClient) (*pb.EventResponse, error) {
					return a.NotifyReviewEvent(ctx, ev)
				}, s.analyzerReviewTimeout}, nil
		case *lookout.PushEvent:
			if st != nil {
				ev.Configuration = *st
			}
			return analyzerNotifier{
				func(ctx context.Context, a lookout.AnalyzerClient) (*pb.EventResponse, error) {
					return a.NotifyPushEvent(ctx, ev)
				}, s.analyzerPushTimeout}, nil
		default:
			ctxlog.Get(ctx).Debugf("ignoring unsupported event: %s", ev)
			return analyzerNotifier{}, fmt.Errorf("unsupported event: %s", ev)
		}
	}
```
the analyzer returned
```
case *lookout.ReviewEvent:
```
![image](https://user-images.githubusercontent.com/2437584/50582749-ffa48000-0e64-11e9-940a-b6d1e9b62c3d.png)
The first comment points to this block of code:
```go
					return a.NotifyReviewEvent(ctx, ev)
				}, s.analyzerReviewTimeout}, nil
		case *lookout.PushEvent:
			if st != nil {
				ev.Configuration = *st
			}
			return analyzerNotifier{
				func(ctx context.Context, a lookout.AnalyzerClient) (*pb.EventResponse, error) {
```
what is not true

And the second comment points to:
```go
		case *lookout.PushEvent:
			if st != nil {
				ev.Configuration = *st
			}
			return analyzerNotifier{
				func(ctx context.Context, a lookout.AnalyzerClient) (*pb.EventResponse, error) {
					return a.NotifyPushEvent(ctx, ev)
				}, s.analyzerPushTimeout}, nil
```
what is ok.

**Comment by smacker** [comment]
Code was re-pushed after the comments were posted. You were looking at the wrong revision. The correct one is here: https://github.com/src-d/lookout/commit/c7aeb3e37d4d1487ecd548356d97793c0c669eef

Both comments point to correct places. You also can see it is correct on PR page:
<img width="711" alt="screenshot 2019-01-10 at 16 25 56" src="https://user-images.githubusercontent.com/406916/50978380-91ab2900-14f4-11e9-8f85-da2b3f11c24c.png">
