### ISSUE TITLE
duplicates on blocks should explain the line range

### ISSUE THREAD

**Issue by dpordomingo** [src-d/lookout-gometalint-analyzer#26]
_related to https://github.com/src-d/lookout-gometalint-analyzer/issues/25_

The comment is a line comment because of a limitation on GitHub code review API, but it applies to a block of code; the comment posted by the analyzer should say so.

I think it should be:
```
+ the code at server/server.go:170-177 is a duplicate of server/server.go:170-177 (dupl)
``` 
instead of the current message
```
- duplicate of server/server.go:170-177 (dupl)
```

**Comment by smacker** [comment]
It is not because of GitHub.
Linter produces the current message for a line not for line range.
You can open an issue in the linter if you want.
