### ISSUE TITLE
Duplicate message in the same line

### ISSUE THREAD

**Issue by dpordomingo** [src-d/lookout-gometalint-analyzer#27]
I think it was caused by a rebase, but the same comment appeared three times in the [lookout#442 PR](https://github.com/src-d/lookout/pull/442/files#r244591878) 

![image](https://user-images.githubusercontent.com/2437584/50594155-b28fd080-0e9b-11e9-8872-1300b514753c.png)

**Comment by smacker** [comment]
Analyzer produces 1 comment on this line.

There is some bug in lookout with skipping it on second/... run. Not related to the analyzer.
